AWSTemplateFormatVersion: '2010-09-09'
Description: CFT to create the Bucket and keys for the central CloudTrail & Logging infrastructure.
Parameters:
  pParentCID:
    Description: Target AlertLogic Account ID that you wish to check
    Type: String

  pDatacenter:
    Description: Data center location
    Type: String
    AllowedValues:
      - "ASHBURN"
      - "DENVER"
      - "NEWPORT"

  pUserName:
    Description: User name to authenticate with Alert Logic portal (or API Access Key)
    Type: String

  pPassword:
    Description: Password to authenticate with Alert Logic portal (or API Secret Key)
    Type: String
    NoEcho: true

  pAPIKey:
    Description: Cloud Defender API Key
    Type: String
    NoEcho: true

Resources:
  LambdaKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: AL Agent Report Lambda KMS Key
      Enabled: 'true'
      EnableKeyRotation: 'true'
      KeyPolicy:
        Version: '2012-10-17'
        Id: key-default-1
        Statement:
        - Sid: Allow administration of the key
          Effect: Allow
          Principal:
            AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
          Action: ['kms:Create*', 'kms:Describe*', 'kms:Enable*', 'kms:List*', 'kms:Put*',
            'kms:Update*', 'kms:Revoke*', 'kms:Disable*', 'kms:Get*', 'kms:Delete*',
            'kms:ScheduleKeyDeletion', 'kms:CancelKeyDeletion', 'kms:Decrypt']
          Resource: '*'
        - Sid: Allow Lambda to use the key
          Effect: Allow
          Principal:
            AWS:
              - !GetAtt [ALAgentReportLambdaRole, Arn]
              - !GetAtt [EncryptionHelperLambdaRole, Arn]
          Action: ['kms:Encrypt', 'kms:Decrypt']
          Resource: '*'

  LambdaKMSKeyAlias:
    Type: "AWS::KMS::Alias"
    Properties:
      AliasName: !Sub "alias/${AWS::StackName}-KMSKey"
      TargetKeyId: !Ref LambdaKMSKey

  EncryptionHelperLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
      - PolicyName: LambdaLogging
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Resource: '*'
            Action: ['logs:*']
            Effect: Allow

  EncryptionHelperLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Encrypt the given payload and return the CipherText
      Runtime: python2.7
      Handler: index.lambda_handler
      Timeout: '180'
      FunctionName: !Sub "${AWS::StackName}-EncryptionHelper"
      Code:
        ZipFile: |
          #Taken from: https://github.com/RealSalmon/lambda-backed-cloud-formation-kms-encryption
          import base64
          import uuid
          import httplib
          import urlparse
          import json
          import boto3
          def send_response(request, response, status=None, reason=None):
              """ Send our response to the pre-signed URL supplied by CloudFormation
              If no ResponseURL is found in the request, there is no place to send a
              response. This may be the case if the supplied event was for testing.
              """

              if status is not None:
                  response['Status'] = status

              if reason is not None:
                  response['Reason'] = reason

              if 'ResponseURL' in request and request['ResponseURL']:
                  url = urlparse.urlparse(request['ResponseURL'])
                  body = json.dumps(response)
                  https = httplib.HTTPSConnection(url.hostname)
                  https.request('PUT', url.path+'?'+url.query, body)

              return response

          def lambda_handler(event, context):

              response = {
                  'StackId': event['StackId'],
                  'RequestId': event['RequestId'],
                  'LogicalResourceId': event['LogicalResourceId'],
                  'Status': 'SUCCESS'
              }

              # PhysicalResourceId is meaningless here, but CloudFormation requires it
              if 'PhysicalResourceId' in event:
                  response['PhysicalResourceId'] = event['PhysicalResourceId']
              else:
                  response['PhysicalResourceId'] = str(uuid.uuid4())

              # There is nothing to do for a delete request
              if event['RequestType'] == 'Delete':
                  return send_response(event, response)

              # Encrypt the value using AWS KMS and return the response
              try:

                  for key in ['KeyId', 'PlainText']:
                      if key not in event['ResourceProperties'] or not event['ResourceProperties'][key]:
                          return send_response(
                              event, response, status='FAILED',
                              reason='The properties KeyId and PlainText must not be empty'
                          )

                  client = boto3.client('kms')
                  encrypted = client.encrypt(
                      KeyId=event['ResourceProperties']['KeyId'],
                      Plaintext=event['ResourceProperties']['PlainText']
                  )

                  response['Data'] = {
                      'CipherText': base64.b64encode(encrypted['CiphertextBlob'])
                  }
                  response['Reason'] = 'The value was successfully encrypted'

              except Exception as E:
                  response['Status'] = 'FAILED'
                  response['Reason'] = 'Encryption Failed - See CloudWatch logs for the Lamba function backing the custom resource for details'
                  print (response)
                  print (E)
              return send_response(event, response)

      Role: !GetAtt [EncryptionHelperLambdaRole, Arn]

  ALAgentReportLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
      - PolicyName: LambdaLogging
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Resource: '*'
            Action: ['logs:*']
            Effect: Allow
      - PolicyName: PublishSNS
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Resource: !Ref ALAgentReportSNS
            Action:
            - sns:Publish

  ALAgentReportSNS:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: AL Agent Report SNS

  ALAgentReportSNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics: [!Ref 'ALAgentReportSNS']
      PolicyDocument:
        Version: '2008-10-17'
        Id: '__default_policy_ID'
        Statement:
        - Sid: __default_statement_ID
          Effect: Allow
          Principal:
            AWS: '*'
          Resource: !Ref ALAgentReportSNS
          Action:
            - SNS:GetTopicAttributes
            - SNS:SetTopicAttributes
            - SNS:AddPermission
            - SNS:RemovePermission
            - SNS:DeleteTopic
            - SNS:Subscribe
            - SNS:ListSubscriptionsByTopic
            - SNS:Publish
            - SNS:Receive
          Condition:
            StringEquals:
              AWS:SourceOwner: !Sub '${AWS::AccountId}'

  ALAgentReportLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Produce AL Agent installation status report
      Runtime: python2.7
      Handler: agent_report_sns.lambda_handler
      Timeout: '180'
      FunctionName: !Sub "${AWS::StackName}-ALAgentReportLambda"
      Code:
        S3Bucket: "welly-gmail-al-agent-report"
        S3Key: "al_agent_install_report_sns.zip"
      Role: !GetAtt [ALAgentReportLambdaRole, Arn]
      Environment:
        Variables:
          PARENT_CID: !Ref pParentCID
          DC: !Ref 'pDatacenter'
          USER: !Ref 'pUserName'
          PASSWORD: !GetAtt ['EncryptedPassword', 'CipherText']
          API_KEY: !GetAtt ['EncryptedAPIKey', 'CipherText']
          SNS_ARN: !Ref ALAgentReportSNS

  EncryptedPassword:
    Type: AWS::CloudFormation::CustomResource
    Version: '1.0'
    Properties:
      ServiceToken: !GetAtt [EncryptionHelperLambda, Arn]
      KeyId: !Ref LambdaKMSKey
      PlainText: !Ref 'pPassword'

  EncryptedAPIKey:
    Type: AWS::CloudFormation::CustomResource
    Version: '1.0'
    Properties:
      ServiceToken: !GetAtt [EncryptionHelperLambda, Arn]
      KeyId: !Ref LambdaKMSKey
      PlainText: !Ref 'pAPIKey'

  ALAgentReportLambdaInvocationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - events.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: ExecuteALAGentReportLambda
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action: ['lambda:InvokeFunction']
            Effect: Allow
            Resource:
            - !GetAtt ALAgentReportLambda.Arn

  ALAgentReportLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ALAgentReportLambda.Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ALAgentReportLambdaScheduledEvent.Arn
      Action: lambda:invokeFunction

  ALAgentReportLambdaScheduledEvent:
    Type: "AWS::Events::Rule"
    Properties:
      Description: !Sub "Execute the ${AWS::StackName}-ALAgentReportLambda on a scheduled basis"
      RoleArn: !GetAtt ALAgentReportLambdaInvocationRole.Arn
      ScheduleExpression: "rate(1 hour)"
      State: ENABLED
      Targets:
        - Arn: !GetAtt ALAgentReportLambda.Arn
          Id: TargetFunction
#TODO: create cloudwatch trigger
